### ISSUE TITLE
There is no tag file for image in Training dataset

### ISSUE THREAD

**Issue by YangChen666** [Mckinsey666/Anime-Generation#1]
Thanks for your sharing！However,I can't find the hair_prob.npy file and eye_prob.npy file in this project.And the training data downloaded from https://drive.google.com/file/d/1jdJXkQIWVGOeb0XJIXE3YuZQeiEPd8rM/view?usp=sharing  doesn't contain a tags.pickle file.Could you please tell me how to get these three files so that I can run train.py successfully?

**Comment by syokujinau** [comment]
同問

**Comment by mymelove02** [comment]
Thanks for your sharing！However,I can't find the hair_prob.npy file and eye_prob.npy file in this project.And the training data downloaded from https://drive.google.com/file/d/1jdJXkQIWVGOeb0XJIXE3YuZQeiEPd8rM/view?usp=sharing doesn't contain a tags.pickle file.Could you please tell me how to get these three files so that I can run train.py successfully?
